### ISSUE TITLE
GetDelegatedAccessToken does not work as expected

### ISSUE THREAD

**Issue by Torgeir-Hansen** [ks-no/fiks-maskinporten-client-dotnet#107]
When fetching a token for a resource delegated through Altinn, there needs to be a consumer_org in the JWT payload, 
as the documentation pointed to by the README (https://docs.digdir.no/docs/Maskinporten/maskinporten_func_delegering.html) states: "Leverandøren må inkludere konsumentens organisasjonsnummer i consumer_org-claimet i JWT-grantet".

The current implementation just adds a consumer_org header when trying to fetch a token.
This does not work, and was also confirmed by Digitaliseringsdirektoratet when I had a meeting with them earlier today to resolve this.
By modifying JwtRequestTokenGenerator.CreateJwtPayload() to add consumer_org when specified, this starts to work.

PR #106 fixes this issue.

One caveat is that the maskinporten documentation states "ID-porten/Maskinporten har allerede to eksisterende interne delegeringsmekanismer, som ikke er kompatible med delegering i Altinn".
.. so this might be something that should be it's own method - depending on what GetDelegatedAccessToken() really was trying to support.

**Comment by zapodot** [comment]
Thank you for your contribution. We will review your PR ASAP and get back to you

**Comment by zapodot** [comment]
Hi @Torgeir-Hansen! Just added a comment to your PR. Please review and make the necessary changes. Apart from that: 👍🏼
