### ISSUE TITLE
Add support for private/public key pairs

### ISSUE THREAD

**Issue by ivanut** [ks-no/fiks-maskinporten-client-dotnet#129]
Hi, 

I have project with the need for using private/public key pairs instead of certificates. Certificates (virksomhetssertificater) can be hard to get, but creating a JWK (JSON Web Key) that is now accepted by Maskinporten is trivial. I have created a PR as a proposal for this feature. The code is tested with my JWK and it works. The PR can be found here: #128. Having this accepted as a new version of the package would be great.

**Comment by Kolbein** [comment]
PR was merged in :rocket:
