### ISSUE TITLE
Kan dere nedgradere til net Standard 2.0?

### ISSUE THREAD

**Issue by JanIvarMoldekleiv** [ks-no/fiks-maskinporten-client-dotnet#17]
Det kan i endel tilfeller være nødvendig å aksessere maskinporten fra .net framework. Dere har oppgradert til .net core 3.1/standard 2.1, og det fører til at man mister kompabilitet mot .net framework:

Se: 
https://docs.microsoft.com/en-us/dotnet/standard/net-standard

"We recommend you target the **lowest version of .NET Standard possible.** So, after you find the highest .NET Standard version you can target, follow these steps:

Target the next lower version of .NET Standard and build your project.
If your project builds successfully, repeat step 1. Otherwise, retarget to the next higher version and that's the version you should use."

****

**Comment by IvanILanekassen** [comment]
Dette er også noe vi er svært interessert i. P.t har vi gjort dette lokalt, men mye bedre at det "offisielle" pakken er tilgjengelig på flest mulig plattformer. Mht konverteringen lokalt så måtte vi fjerne to tilfeller av nullable reference types og endre på en GetHashCode implementasjon. Jeg kan evt lage en PR dere kan se på, hvis dette er ønskelig?

**Comment by IvanILanekassen** [comment]
Hei igjen, 

Jeg har nå laget https://github.com/ks-no/fiks-maskinporten-client-dotnet/pull/18, fint om dere kan ta en titt.

Vennlig hilsen,
Ivan Uthus

**Comment by zapodot** [comment]
Hei! Skal få nedgradert til 2.0 slik at det blir lettere for dere å bruke biblioteket

**Comment by IvanILanekassen** [comment]
OK, så bra. 

Etter å ha tatt i bruk vår egen fork av dette, så har vi kommet over følgende issues:
•	Vi trenger signerte (strongly named) assemblies, noe deres klient ikke er. Vet ikke om det er aktuelt for dere å innføre strongly named assemblies?
•	Sertifikatstøtten fungerer bedre på .NET Core enn på .NET. Vi måtte derfor gjøre endringer i koden for å få signeringen av de utgående meldingene til å fungere. Jeg kan evt lage en ny PR med de endringene?
•	Vi har oppgradert til versjon 7.3.0 av JWT pakken (vi fant også en bug hos dem som de har fikset i versjon 7.3.0).

Vennlig hilsen,
Ivan Uthus

**Comment by zapodot** [comment]
* vi kommer ikke til å støtte strongly named assemblies. .Net er ikke vår hovedplattform og vi ønsker derfor å basere oss hovedaklig på .net core. I følge Microsoft har strongly named assemblies [ingen fordeler](https://docs.microsoft.com/en-us/dotnet/standard/assembly/strong-named) i .net core. Vi ønsker derimot å støtte netstandard 2.0 slik at det lar seg gjøre å bruke våre klienter også på .net plattformen, så vi håper derfor dere kan fravike dette kravet
* kom gjerne med en PR på forbedret sertifikatstøtte om du har mulighet til det
* vi har allerede en åpen issue på å oppgradere til siste versjon av JWT avhengiheten #11 . Skal få sett på det

**Comment by zapodot** [comment]
Støtte for netstandard 2.0 er nå released i v. 1.0.4 https://www.nuget.org/packages/KS.Fiks.Maskinporten.Client/1.0.4
